### Data Fetching From API

In [ ]:
## API - Application Programming Interface

    - it data pipeline (communicate two software)
    - it send data/information from point 1 to point 2
    - data--> format of Json

In [ ]:
## 2 API's

TDMB API - "https://developers.themoviedb.org/"
RapidAPI - "https://rapidapi.com/collection/list-of-free-apis"
JSON Viewer - "http://jsonviewer.stack.hu/"

In [1]:
import pandas as pd
import requests

In [20]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [5]:
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,206.478,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.708,27715
1,False,/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",202.241,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.689,21021
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,124.407,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.570,12691
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,135.543,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.600,16141
4,False,/bxgTSUenZDHNFerQ1whRKplrMKF.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,90.609,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.500,8871
5,False,/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",100.756,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,Spirited Away,False,8.538,16813
6,False,/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",38.899,/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.521,4459
7,False,/oOv2oUXcAaNXakRqUPxYq5lJURz.jpg,"[18, 28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,205.376,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,The Dark Knight,False,8.519,33406
8,False,/vxJ08SvwomfKbpboCWynC3uqUg4.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,114.815,/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg,1999-12-10,The Green Mile,False,8.500,17795
9,False,/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",133.101,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.500,18647
10,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",139.682,/jYqKxBbAUdfKq3BfHKivJytFiPL.jpg,1994-09-10,Pulp Fiction,False,8.500,28315
11,False,/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg,"[16, 10749, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,95.875,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,Your Name.,False,8.487,11581
12,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,172.847,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,The Lord of the Rings: The Return of the King,False,8.484,24650
13,False,/mzfx54nfDPTUXZOG48u4LaEheDy.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,119.966,/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg,1994-06-23,Forrest Gump,False,8.469,27830
14,False,/x4biAVdPVCghBlsVIzB6NmbghIz.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,91.966,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-22,"The Good, the Bad and the Ugly",False,8.500,8803
15,False,/7TF4p86ZafnxFuNqWdhpHXFO244.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",79.563,/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg,1990-09-12,GoodFellas,False,8.500,13111
16,False,/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg,"[28, 18]",346,ja,七人の侍,A samurai answers a village's request for prot...,39.933,/ApdijpVm1GNV9BQMOsGcAXq4gEB.jpg,1954-04-26,Seven Samurai,False,8.456,3789
17,False,/vgnoBSVzWAV9sNQUORaDGvDp7wx.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,330.283,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,2014-11-05,Interstellar,False,8.500,36482
18,False,/tDFvXn4tane9lUvFAFAUkMylwSr.jpg,"[16, 18, 10752]",12477,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.062,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-16,Grave of the Fireflies,False,8.451,5710
19,False,/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg,"[35, 18]",637,it,La vita è bella,A touching story of an Italian book seller of ...,61.338,/74hLDKjD5aGYOotO6esUVaeISa2.jpg,1997-12-20,Life Is Beautiful,False,8.447,13188

In [6]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [8]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,206.478,8.708,27715
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,202.241,8.689,21021
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,124.407,8.570,12691
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,135.543,8.600,16141
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,90.609,8.500,8871

In [9]:
df = pd.DataFrame()

In [10]:
df

Empty DataFrame
Columns: []
Index: []

In [15]:

for i in range(1, 429):
    response = requests.get(f'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={i}')
    
    # Extract data from JSON response
    temp_df = pd.DataFrame(response.json().get('results', []), 
                           columns=['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count'])

    # Use pd.concat instead of append
    df = pd.concat([df, temp_df], ignore_index=True)

# Display the first few rows
print(df.head())

    id                     title  \
0  278  The Shawshank Redemption
1  238             The Godfather
2  240     The Godfather Part II
3  424          Schindler's List
4  389              12 Angry Men

                                            overview release_date  popularity  \
0  Imprisoned in the 1940s for the double murder ...   1994-09-23     206.478
1  Spanning the years 1945 to 1955, a chronicle o...   1972-03-14     202.241
2  In the continuing saga of the Corleone crime f...   1974-12-20     124.407
3  The true story of how businessman Oskar Schind...   1993-12-15     135.543
4  The defense and the prosecution have rested an...   1957-04-10      90.609

   vote_average  vote_count
0         8.708       27715
1         8.689       21021
2         8.570       12691
3         8.600       16141
4         8.500        8871

In [16]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,206.478,8.708,27715
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,202.241,8.689,21021
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,124.407,8.570,12691
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,135.543,8.600,16141
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,90.609,8.500,8871
...,...,...,...,...,...,...,...
17115,17127,The Object of My Affection,A pregnant New York social worker begins to de...,1998-04-17,9.334,5.800,306
17116,10768,The Final Conflict,Damien Thorn has helped rescue the world from ...,1981-03-20,15.622,5.819,576
17117,8836,The X Files: I Want to Believe,Six years after the events of The X-Files seri...,2008-07-24,18.327,5.800,1514
17118,354861,Father Figures,Upon learning that their mother has been lying...,2017-12-21,11.069,5.818,631
17119,14035,Meatballs,Tripper is the head counselor at a budget summ...,1979-06-28,19.591,5.825,317

In [17]:
df.shape

(17120, 7)

In [21]:
df.to_csv('movies2.csv')